Disable workflows from running automatically

diff --git a/.github/workflows/covid-data-news.yml b/.github/workflows/covid-data-news.yml
--- a/.github/workflows/covid-data-news.yml
+++ b/.github/workflows/covid-data-news.yml
@@ -1,127 +1,128 @@
-# # This is a basic workflow to help you get started with Actions
+# This is a basic workflow to help you get started with Actions
 
-# name: news.json update
+name: news.json update
 
-# # Controls when the action will run. Triggers the workflow on push or pull request
-# # events but only for the master branch
-# on:
-#   push:
-#     branches: [ master ]
-#   # schedule:
-#   #   - cron: 0 */3 * * *
+# Controls when the action will run. Triggers the workflow on push or pull request
+# events but only for the master branch
+on:
+  workflow_dispatch
+  # push:
+  #   branches: [ master ]
+  # schedule:
+  #   - cron: 0 */3 * * *
 
-# jobs:
-#   # This workflow contains a single job called "build"
-#   build:
-#     # The type of runner that the job will run on
-#     runs-on: ubuntu-latest
+jobs:
+  # This workflow contains a single job called "build"
+  build:
+    # The type of runner that the job will run on
+    runs-on: ubuntu-latest
 
-#     # Steps represent a sequence of tasks that will be executed as part of the job
-#     steps:
-#     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-#     - uses: actions/checkout@v2
+    # Steps represent a sequence of tasks that will be executed as part of the job
+    steps:
+    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+    - uses: actions/checkout@v2
 
-#     - name: Log workspace path
-#       run: |
-#         echo "WORKSPACE: '${GITHUB_WORKSPACE}'"
+    - name: Log workspace path
+      run: |
+        echo "WORKSPACE: '${GITHUB_WORKSPACE}'"
 
-#     # Install Python
-#     - name: Set up Python 3.x
-#       uses: actions/setup-python@v1
-#       with:
-#         python-version: '3.x'
+    # Install Python
+    - name: Set up Python 3.x
+      uses: actions/setup-python@v1
+      with:
+        python-version: '3.x'
     
-#     - name: Install Data Scraper & Dependencies
-#       run: |
-#         cd ..
-#         git clone https://github.com/sfbrigade/data-covid19-sfbayarea.git
-#         cd data-covid19-sfbayarea
-#         python -m pip install --upgrade pip
-#         pip install -r requirements.txt;
-#         # # By default, this puts a symlink to the geckodriver binary at:
-#         # #   /home/runner/.local/share/WebDriverManager/bin/geckodriver
-#         # # But that's not on the PATH
-#         # DRIVER_PATH="$(pwd)/env/bin"
-#         # mkdir -p "${DRIVER_PATH}"
-#         # export PATH="${DRIVER_PATH}:${PATH}"
-#         # webdrivermanager firefox --linkpath "${DRIVER_PATH}"
-#         echo "PWD: $(pwd)"
-#         echo "PATH: ${PATH}"
+    - name: Install Data Scraper & Dependencies
+      run: |
+        cd ..
+        git clone https://github.com/sfbrigade/data-covid19-sfbayarea.git
+        cd data-covid19-sfbayarea
+        python -m pip install --upgrade pip
+        pip install -r requirements.txt;
+        # # By default, this puts a symlink to the geckodriver binary at:
+        # #   /home/runner/.local/share/WebDriverManager/bin/geckodriver
+        # # But that's not on the PATH
+        # DRIVER_PATH="$(pwd)/env/bin"
+        # mkdir -p "${DRIVER_PATH}"
+        # export PATH="${DRIVER_PATH}:${PATH}"
+        # webdrivermanager firefox --linkpath "${DRIVER_PATH}"
+        echo "PWD: $(pwd)"
+        echo "PATH: ${PATH}"
 
-#         echo "::set-env name=SCRAPER_PATH::$(pwd)"
+        echo "::set-env name=SCRAPER_PATH::$(pwd)"
         
-#         # Keep track of the version used so we can use it in commit messages
-#         echo "::set-env name=SCRAPER_COMMIT::$(git rev-parse HEAD)"
+        # Keep track of the version used so we can use it in commit messages
+        echo "::set-env name=SCRAPER_COMMIT::$(git rev-parse HEAD)"
 
 
-#     - name: Scrape News
-#       run: |
-#         # TODO: try setting up Headless FF so we can drop xvfb
-#         # Reason for "-nolisten tcp", not documented within Xvfb manpages (for who knows what reason)
-#         # https://superuser.com/questions/855019/make-xvfb-listen-only-on-local-ip
-#         #export DISPLAY=:99
-#         #export DBUS_SESSION_BUS_ADDRESS=/dev/null
-#         #Xvfb :99 -screen 0 640x480x8 -nolisten tcp &
+    - name: Scrape News
+      run: |
+        # TODO: try setting up Headless FF so we can drop xvfb
+        # Reason for "-nolisten tcp", not documented within Xvfb manpages (for who knows what reason)
+        # https://superuser.com/questions/855019/make-xvfb-listen-only-on-local-ip
+        #export DISPLAY=:99
+        #export DBUS_SESSION_BUS_ADDRESS=/dev/null
+        #Xvfb :99 -screen 0 640x480x8 -nolisten tcp &
         
-#         echo "PWD: $(pwd)"
-#         # See: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
-#         echo "Geckodriver: ${GECKOWEBDRIVER}"
-#         #export LOCAL_BIN="$(pwd)/env/bin"
-#         #mkdir -p "${LOCAL_BIN}"
-#         #ln -s "${GECKOWEBDRIVER}" "${LOCAL_BIN}/geckodriver"
-#         #export PATH="${LOCAL_BIN}:${PATH}"
-#         mkdir -p data
-#         cd $SCRAPER_PATH
-#         echo "::set-env name=SCRAPER_TIME::$(date)"
-#         python scraper_news.py --format json_simple alameda > "${GITHUB_WORKSPACE}/data/news_alameda.json" || (echo "" && echo "GECKODRIVER LOGS:" && cat geckodriver.log && fail)
+        echo "PWD: $(pwd)"
+        # See: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
+        echo "Geckodriver: ${GECKOWEBDRIVER}"
+        #export LOCAL_BIN="$(pwd)/env/bin"
+        #mkdir -p "${LOCAL_BIN}"
+        #ln -s "${GECKOWEBDRIVER}" "${LOCAL_BIN}/geckodriver"
+        #export PATH="${LOCAL_BIN}:${PATH}"
+        mkdir -p data
+        cd $SCRAPER_PATH
+        echo "::set-env name=SCRAPER_TIME::$(date)"
+        python scraper_news.py --format json_simple alameda > "${GITHUB_WORKSPACE}/data/news_alameda.json" || (echo "" && echo "GECKODRIVER LOGS:" && cat geckodriver.log && fail)
     
-#     - name: Scrape Data
+    - name: Scrape Data
+      run: |
+        echo "PWD: $(pwd)"
+        # See: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
+        echo "Geckodriver: ${GECKOWEBDRIVER}"
+        #export LOCAL_BIN="$(pwd)/env/bin"
+        #mkdir -p "${LOCAL_BIN}"
+        #ln -s "${GECKOWEBDRIVER}" "${LOCAL_BIN}/geckodriver"
+        #export PATH="${LOCAL_BIN}:${PATH}"
+        mkdir -p data
+        cd $SCRAPER_PATH
+        echo "::set-env name=SCRAPER_TIME::$(date)"
+        python scraper_data.py > "${GITHUB_WORKSPACE}/data/data.json" || (echo "" && echo "GECKODRIVER LOGS:" && cat geckodriver.log && fail)
+
+#     - name: Commit Changes
 #       run: |
-#         echo "PWD: $(pwd)"
-#         # See: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
-#         echo "Geckodriver: ${GECKOWEBDRIVER}"
-#         #export LOCAL_BIN="$(pwd)/env/bin"
-#         #mkdir -p "${LOCAL_BIN}"
-#         #ln -s "${GECKOWEBDRIVER}" "${LOCAL_BIN}/geckodriver"
-#         #export PATH="${LOCAL_BIN}:${PATH}"
-#         mkdir -p data
-#         cd $SCRAPER_PATH
-#         echo "::set-env name=SCRAPER_TIME::$(date)"
-#         python scraper_data.py > "${GITHUB_WORKSPACE}/data/data.json" || (echo "" && echo "GECKODRIVER LOGS:" && cat geckodriver.log && fail)
+#         if [[ "$(git status --porcelain)" =~ 'data/' ]]; then
+#           # Configure git
+#           git config user.name ${{ secrets.githubaction_config_user_name }}
+#           git config user.email ${{ secrets.githubaction_config_user_email }}
 
-# #     - name: Commit Changes
-# #       run: |
-# #         if [[ "$(git status --porcelain)" =~ 'data/' ]]; then
-# #           # Configure git
-# #           git config user.name ${{ secrets.githubaction_config_user_name }}
-# #           git config user.email ${{ secrets.githubaction_config_user_email }}
+#           echo 'Committing updated news data...'
+#           git add data/
+#           git commit -m "GitHubAction: news data update.
 
-# #           echo 'Committing updated news data...'
-# #           git add data/
-# #           git commit -m "GitHubAction: news data update.
+#           Created with commit ${SCRAPER_COMMIT} from sfbrigade/data-covid19-sfbayarea
+#           https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${SCRAPER_COMMIT}
+#           "
+#           git push
+#           echo "Committed: $(git show HEAD --no-patch --format=reference)"
+#           echo 'You should make a pull request to put these changes on master!'
+#         else
+#           echo 'Nothing to commit!'
+#         fi
 
-# #           Created with commit ${SCRAPER_COMMIT} from sfbrigade/data-covid19-sfbayarea
-# #           https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${SCRAPER_COMMIT}
-# #           "
-# #           git push
-# #           echo "Committed: $(git show HEAD --no-patch --format=reference)"
-# #           echo 'You should make a pull request to put these changes on master!'
-# #         else
-# #           echo 'Nothing to commit!'
-# #         fi
-
-#     - name: Make PR for Changes
-#       uses: peter-evans/create-pull-request@v2
-#       with:
-#         branch: test-auto-pr-branch
-#         title: 'GitHubAction: news data update'
-#         body: |
-#           Created with commit ${{env.SCRAPER_COMMIT}} from sfbrigade/data-covid19-sfbayarea
-#           https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}}
+    - name: Make PR for Changes
+      uses: peter-evans/create-pull-request@v2
+      with:
+        branch: test-auto-pr-branch
+        title: 'GitHubAction: news data update'
+        body: |
+          Created with commit ${{env.SCRAPER_COMMIT}} from sfbrigade/data-covid19-sfbayarea
+          https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}}
           
-#           Scraped at: ${{ env.SCRAPER_TIME }}
-#         commit-message: |
-#           GitHubAction: news data update
+          Scraped at: ${{ env.SCRAPER_TIME }}
+        commit-message: |
+          GitHubAction: news data update
           
-#           Created with commit ${{env.SCRAPER_COMMIT}} from sfbrigade/data-covid19-sfbayarea
-#           https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}}
+          Created with commit ${{env.SCRAPER_COMMIT}} from sfbrigade/data-covid19-sfbayarea
+          https://github.com/sfbrigade/data-covid19-sfbayarea/commit/${{env.SCRAPER_COMMIT}}
