Test whether I needed to rename gecko_driver

diff --git a/.github/workflows/covid-data-news.yml b/.github/workflows/covid-data-news.yml
--- a/.github/workflows/covid-data-news.yml
+++ b/.github/workflows/covid-data-news.yml
@@ -67,13 +67,13 @@ jobs:
         echo "PWD: $(pwd)"
         # See: https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
         echo "Geckodriver: ${GECKOWEBDRIVER}"
-        export LOCAL_BIN="$(pwd)/env/bin"
-        mkdir -p "${LOCAL_BIN}"
-        ln -s "${GECKOWEBDRIVER}" "${LOCAL_BIN}/geckodriver"
-        export PATH="${LOCAL_BIN}:${PATH}"
+        #export LOCAL_BIN="$(pwd)/env/bin"
+        #mkdir -p "${LOCAL_BIN}"
+        #ln -s "${GECKOWEBDRIVER}" "${LOCAL_BIN}/geckodriver"
+        #export PATH="${LOCAL_BIN}:${PATH}"
         mkdir -p data
         cd $SCRAPER_PATH
-        python scraper_news.py --format json_simple alameda > "${GITHUB_WORKSPACE}/data/news_alameda.json" || (echo "" && echo "GECKODRIVER LOGS:" && cat geckodriver.log)
+        python scraper_news.py --format json_simple alameda > "${GITHUB_WORKSPACE}/data/news_alameda.json" || (echo "" && echo "GECKODRIVER LOGS:" && cat geckodriver.log && fail)
     
     - name: Commit Changes
       run: |
