Simplify!

diff --git a/.github/workflows/covid-data-data.yml b/.github/workflows/covid-data-data.yml
--- a/.github/workflows/covid-data-data.yml
+++ b/.github/workflows/covid-data-data.yml
@@ -47,33 +47,40 @@ jobs:
         # Keep track of the version used so we can use it in commit messages
         echo "::set-env name=SCRAPER_COMMIT::$(git rev-parse HEAD)"
         
+    # - name: Scrape Data
+    #   # Use a custom shell so individual commands don't fail. We want to run
+    #   # each county independently and keep the output from the ones that
+    #   # succeed. We'll keep track of what failed and manually fail at the end.
+    #   # at the end.
+    #   shell: bash {0}
+    #   run: |
+    #     echo "::set-env name=SCRAPER_TIME::$(date)"
+
+    #     counties='alameda contra_costa marin napa san_francisco san_mateo santa_clara solano sonoma'
+    #     cd ${GITHUB_WORKSPACE}/scraper
+    #     mkdir county_output
+    #     OUTPUT_FILE="${GITHUB_WORKSPACE}/site/data/data.v2.json"
+    #     ERROR=''
+    #     for county in $counties; do
+    #       python scraper_data.py "${county}" > "county_output/${county}.json"
+    #       if [ "${?}" -ne 0 ]; then ERROR=true; fi
+    #     done
+
+    #     # Merge all the new data on top of the old data and save.
+    #     cp "${OUTPUT_FILE}" base.json
+    #     jq -s 'reduce .[] as $county ({}; . + $county)' base.json county_output/*.json > "${OUTPUT_FILE}"
+
+    #     # Exit with an error if any of the scrapers failed.
+    #     if [ -n "${ERROR}" ]; then
+    #       exit 1
+    #     fi
+
     - name: Scrape Data
-      # Use a custom shell so individual commands don't fail. We want to run
-      # each county independently and keep the output from the ones that
-      # succeed. We'll keep track of what failed and manually fail at the end.
-      # at the end.
-      shell: bash {0}
       run: |
         echo "::set-env name=SCRAPER_TIME::$(date)"
-
-        counties='alameda contra_costa marin napa san_francisco san_mateo santa_clara solano sonoma'
         cd ${GITHUB_WORKSPACE}/scraper
-        mkdir county_output
         OUTPUT_FILE="${GITHUB_WORKSPACE}/site/data/data.v2.json"
-        ERROR=''
-        for county in $counties; do
-          python scraper_data.py "${county}" > "county_output/${county}.json"
-          if [ "${?}" -ne 0 ]; then ERROR=true; fi
-        done
-
-        # Merge all the new data on top of the old data and save.
-        cp "${OUTPUT_FILE}" base.json
-        jq -s 'reduce .[] as $county ({}; . + $county)' base.json county_output/*.json > "${OUTPUT_FILE}"
-
-        # Exit with an error if any of the scrapers failed.
-        if [ -n "${ERROR}" ]; then
-          exit 1
-        fi
+        python scraper_data.py > "${GITHUB_WORKSPACE}/site/data/data.v2.json"
 
     - name: Create PR if New Data
       uses: peter-evans/create-pull-request@v2
